import { Eye, MoreHorizontal, Pencil, Power, Trash2 } from 'lucide-react';

const roleClass = (role) => ({
  admin: 'bg-indigo-50 text-indigo-700 dark:bg-indigo-950/60 dark:text-indigo-300',
  supervisor: 'bg-amber-50 text-amber-700 dark:bg-amber-950/50 dark:text-amber-300',
  employee: 'bg-emerald-50 text-emerald-700 dark:bg-emerald-950/50 dark:text-emerald-300',
}[role] || 'bg-slate-100 text-slate-600');

export default function UserTable({ users, loading, sort, onSort, onView, onEdit, onToggleStatus, onDelete, onMore }) {
  const heading = (label, field) => <button onClick={() => onSort(field)} className="inline-flex items-center gap-1">{label}{sort.field === field && <span className="text-indigo-500">{sort.direction === 'asc' ? '↑' : '↓'}</span>}</button>;
  if (loading) return <div className="p-8 text-center text-sm text-slate-400">Loading users…</div>;
  if (!users.length) return <div className="p-10 text-center text-sm text-slate-400">No users match the selected filters.</div>;
  return <div className="table-container overflow-x-auto"><table className="w-full min-w-[820px]"><thead><tr className="bg-slate-50/80 dark:bg-slate-800/60"><th className="table-header">{heading('User', 'fullName')}</th><th className="table-header">{heading('Role', 'role')}</th><th className="table-header">{heading('Department', 'department')}</th><th className="table-header">Employee ID</th><th className="table-header">{heading('Joined On', 'createdDate')}</th><th className="table-header">{heading('Status', 'status')}</th><th className="table-header text-center">Actions</th></tr></thead><tbody>{users.map(user => <tr key={user.id} className="table-row"><td className="table-cell"><div className="flex items-center gap-2.5"><span className="grid h-9 w-9 place-items-center rounded-full bg-gradient-to-br from-indigo-500 to-violet-600 text-xs font-bold text-white">{user.fullName?.split(' ').map(part => part[0]).slice(0, 2).join('')}</span><div><p className="font-semibold text-slate-800 dark:text-slate-100">{user.fullName}</p><p className="text-[11px] text-slate-400">{user.email || user.username}</p></div></div></td><td className="table-cell"><span className={`rounded-full px-2.5 py-1 text-xs font-semibold capitalize ${roleClass(user.role)}`}>{user.role}</span></td><td className="table-cell font-medium text-slate-600 dark:text-slate-300">{user.department}</td><td className="table-cell font-mono text-xs font-semibold text-slate-600 dark:text-slate-300">{user.employeeId || '—'}</td><td className="table-cell text-xs text-slate-500">{user.createdDate}</td><td className="table-cell"><span className={user.status === 'active' ? 'badge-active' : 'badge-inactive'}><span className={`mr-1.5 h-1.5 w-1.5 rounded-full ${user.status === 'active' ? 'bg-emerald-500' : 'bg-slate-400'}`} />{user.status}</span></td><td className="table-cell"><div className="flex justify-center gap-1"><button onClick={() => onView(user)} className="user-action" title="View user"><Eye size={15} /></button><button onClick={() => onEdit(user)} className="user-action" title="Edit user"><Pencil size={15} /></button><button onClick={() => onToggleStatus(user)} className="user-action text-amber-600 hover:bg-amber-50" title="Activate or deactivate"><Power size={15} /></button><button onClick={() => onDelete(user)} className="user-action text-red-500 hover:bg-red-50" title="Delete user"><Trash2 size={15} /></button><button onClick={() => onMore(user)} className="user-action" title="Change role"><MoreHorizontal size={16} /></button></div></td></tr>)}</tbody></table></div>;
}
